
#' Unnest a list-column with preservation of empty lists
#'
#' This function is a wrapper around `tidyr::unnest()`. It defaults to keeping rows with empty lists,
#' which can be crucial for maintaining data integrity and avoiding accidental data loss. This wrapper
#' excludes deprecated parameters.
#'
#' @param data A data frame with a list-column to unnest.
#' @param cols Columns to unnest, if not specified, it defaults to all list-columns.
#' @param keep_empty A logical indicating whether to keep rows with empty lists.
#'                   Defaults to TRUE.
#' @param ptype An optional prototype used to control the output type.
#' @param names_sep If non-NULL, the names of the new columns are generated by combining the name of the
#'                  original column, and the names of the elements of the nested data frames with the specified
#'                  separator.
#' @param names_repair What happens if the output has non-unique names? Options are "minimal", "unique",
#'                     "universal", and "check_unique". Default is "check_unique".
#' @return A tibble with the list-column unnested.
#' @export
#' @examples
#' \dontrun{
#' df <- tibble(x = 1:3, y = list(1:2, integer(0), 3:5))
#' unnest_keep(df, y)
#' }
unnest_keep <- function(data, cols, keep_empty = TRUE, ptype = NULL, names_sep = NULL,
                        names_repair = "check_unique") {
  tidyr::unnest(data, {{cols}}, keep_empty = keep_empty, ptype = ptype,
                names_sep = names_sep, names_repair = names_repair)
}
